### ISSUE TITLE
Support other required, unstable options

### ISSUE THREAD

**Issue by nrc** [rust-dev-tools/rls-rustc#3]
The RLS needs `-Zcontinue-parse-after-error`

This will require some more API in rustc, I think.

We also need `--error-format=json`, but that is stable so can just be passed normally.

Will Rustdoc need other options? cc @steveklabnik

**Comment by nrc** [comment]
Blocked on https://github.com/rust-lang/rust/pull/43730

**Comment by steveklabnik** [comment]
The only option we use is `-Z save-analysis`
